FROM mzz2017/git:alpine AS version
WORKDIR /build
ADD .git ./.git
RUN git describe --abbrev=0 --tags | tee ./version

FROM alpine:latest AS builder
COPY ./install/docker/docker_helper.sh ./docker_helper.sh
COPY ./version ./version
RUN sh -c "$(cat ./docker_helper.sh)"
RUN apk add --no-cache iptables ip6tables nftables
RUN rm ./docker_helper.sh
EXPOSE 2017
VOLUME /etc/v2raya
ENTRYPOINT ["v2raya"]
