FROM mzz2017/git:alpine AS version
WORKDIR /build
ADD .git ./.git
RUN git describe --abbrev=0 --tags | tee ./version

FROM alpine:latest AS builder
RUN sh -c "$(cat ./docker_helper.sh)"
RUN apk add --no-cache iptables ip6tables nftables
EXPOSE 2017
VOLUME /etc/v2raya
ENTRYPOINT ["v2raya"]
